.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WHONIX\-SETUP\-WIZARD" "8" "April 2020" "whonix-setup-wizard" "whonix-setup-wizard Manual"
.SH "NAME"
\fBwhonix\-setup\-wizard\fR \- Whonix Settings Wizard
.P
.SH "SYNOPSIS"
\fBwhonix\-setup\-wizard\fR {setup,locale_settings}
.SH "DESCRIPTION"
Graphical version of \fBwhonixsetup\fR, that asks in which environment you are using Whonix, informs about various situations, helps to enable Tor in Tor config\.
.SH "EXAMPLES"
\fBwhonix\-setup\-wizard setup\fR
.P
\fBwhonix\-setup\-wizard locale_settings\fR
.SH "SKIP FILES"
See also \fBman whonixsetup\fR for skip files\.
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
