#!/usr/bin/python3 -u

from subprocess import call
import sys, os
import time
import distutils.spawn


def whonix_setup_wizard_start():
   whonix_setup_wizard = distutils.spawn.find_executable("whonix-setup-wizard")
   if whonix_setup_wizard == None:
      print('whonix-setup-wizard not found! Exiting.')
      sys.exit(1)

   command = 'xhost +local:root'
   call(command, shell = True)

   command = 'kdesudo {} setup'.format(whonix_setup_wizard)
   call(command, shell=True)


if os.path.exists('/var/run/qubes/this-is-templatevm'):
   print('/var/run/qubes/this-is-templatevm exists. Exiting.')
   sys.exit()

if os.path.exists('/var/cache/whonix-setup-wizard/status-files/whonixsetup.skip'):
   print('/var/cache/whonix-setup-wizard/status-files/whonixsetup.skip exists. Exiting.')
   sys.exit()


if os.path.exists('/usr/share/anon-gw-base-files/gateway'):
    ## Qubes-Whonix only.
    ## Display alert that 'whonix-tor-disable' service flag is set and it will need to
    ## to manually unset if user wants to be able to boot with Tor enabled.
    ## TODO: Don't depend on qubes-whonix package / 'alert' script by qubes-whonix package.
    ##       Abolish 'alert' script. Merge into whonixcheck and/or anon-connection-wizard.
    ##       https://phabricator.whonix.org/T656
    if os.path.exists('/var/run/qubes-service/whonix-tor-disable'):
        command = '/usr/lib/qubes-whonix/alert tor-disabled /usr/lib/qubes-whonix/messages.yaml'
        call(command, shell = True)
        sys.exit()

    ## TODO: Make sure systemd unit tor@default starts before /etc/xdg/autostart/whonix-setup-wizard.desktop
    #command = 'systemctl --no-pager status tor@default'
    #tor_status_code = call(command, shell=True)
    #if tor_status_code != 0:
       #print('Starting whonix-setup-wizard because Tor systemd unit is not running. \
#This could be because of a Tor configuration issue.')
       #whonix_setup_wizard_start()
       #sys.exit()

    ## We cannot depend on anon-connection-wizard because it would be confusing to have
    ## it installed on Whonix-Workstation.
    ## What if whonix-setup-wizard is installed but anon-connection-wizard not? Well, in that
    ## case the user should be knowing what the user is doing. Happens only in cases where
    ## the user does not use Whonix's default anon-meta-packages. In that case just error out.
    from anon_connection_wizard import tor_status
    tor_status = tor_status.tor_status()

    if tor_status == 'tor_enabled':
       print('Tor already enabled. Exiting.')
       sys.exit()

    print(tor_status)

    whonix_setup_wizard_start()


elif os.path.exists('/usr/share/anon-ws-base-files/workstation'):

    if (os.path.exists('/var/cache/whonix-setup-wizard/status-files/whonixsetup.done') or
                               os.path.exists('/var/lib/whonix/do_once/whonixsetup.done')):
       print('whonix-setup-wizard done file exists. Exiting.')
       sys.exit()

    whonix_setup_wizard_start()


else:

    print('Neither Whonix-Gateway nor Whonix-Workstation detected. Exiting.')
    sys.exit(1)
