#!/usr/bin/python3 -u

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import shutil

whonix_setup_wizard = shutil.which("whonix-setup-wizard")
if whonix_setup_wizard == None:
   print('ERROR: whonix-setup-wizard not found! Exiting.')
   sys.exit(1)

command = 'xhost +local:root'
call(command, shell = True)

command = 'kdesudo {} setup'.format(whonix_setup_wizard)
call(command, shell=True)
