#!/usr/bin/python

from subprocess import call
import sys, os
import time
import distutils.spawn

def tor_status():
    if not os.path.exists('/etc/tor/torrc'):
        # TODO: add gui message.
        return 'no_torrc'

    fh = open('/etc/tor/torrc','r')
    lines = fh.readlines()
    fh.close()

    for line in lines:
        if line.strip() == '#DisableNetwork 0':
            return 'tor_disabled'


if os.path.exists('/usr/share/anon-gw-base-files/gateway'):

    #command = '/usr/lib/gateway_first_run_notice'
    #call(command, shell = True)
    #time.sleep(0.5)

    whonix_setup_wizard = distutils.spawn.find_executable("whonix-setup-wizard")
    if not whonix_setup_wizard == "":
        tor_status = tor_status()
        if tor_status == 'tor_disabled':
            command = 'xhost +local:root'
            call(command, shell = True)

            command = 'sudo %s setup' % (whonix_setup_wizard)
            call(command, shell=True)

    else:
        # revert to cli. TODO: add gui message.
        command = '/usr/lib/whonixsetup_cli_start_maybe'
        call(command, shell = True)

elif os.path.exists('/usr/share/anon-ws-base-files/workstation'):

    if not os.path.exists('/var/cache/whonix-setup-wizard/status-files/whonixsetup.done'):
        whonix_setup_wizard = distutils.spawn.find_executable("whonix-setup-wizard")
        if not whonix_setup_wizard == "":
            command = 'xhost +local:root'
            call(command, shell = True)

            command = 'sudo %s setup' % (whonix_setup_wizard)
            call(command, shell=True)
