#!/usr/bin/python

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import distutils.spawn

command = 'xhost +local:root'
call(command, shell = True)

whonix_setup_wizard = distutils.spawn.find_executable("whonix-setup-wizard")
if not whonix_setup_wizard == "":
    command = 'kdesudo %s repository' % (whonix_setup_wizard)
    call(command, shell=True)
