#!/usr/bin/python

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time

command = 'xhost +local:root'
call(command, shell = True)

command = 'sudo /usr/bin/whonix-setup-wizard setup'
call(command, shell = True)
